# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=256, verbose_name='地址'),
            preserve_default=False,
        ),
    ]
